### ISSUE TITLE
model not found！(fuzzy_cm_5s_ekf.json)

### ISSUE THREAD

**Issue by hejiakia** [iag0g0mes/t2fis_driving_style#2]
Hello lago，
	parser.add_argument(
		"--model_dir",
		required=True,
		type=str,
		help="Directory where the model is saved",
	)

	parser.add_argument(
		"--result_dir",
		required=True,
		type=str,
		help="Directory where the model is saved",
	)

How is the model file obtained？

Thanks and regards,
he

**Comment by iag0g0mes** [comment]
Hello!

what  .py file are you trying to run?

**Comment by hejiakia** [comment]
> Hello!
> 
> what .py file are you trying to run?

fuzzy_c_means.py
```
def process(data:np.ndarray,
			obs_len:int,
			filter_name:str,
			model_dir:str,
			result_dir:str,
			mode:str)->NoReturn:

	model_file=f'fuzzy_cm_{obs_len}s_{filter_name}.json'
	assert os.path.exists(os.path.join(model_dir, model_file)),\
		f'[Fuzzy C-Means][{mode}][ERROR] model not found! ({model_file})'
```

**Comment by iag0g0mes** [comment]
I'm sorry, I just noticed that there isn't a proper usage description in the README. 

In your case, you first need to run the code in train mode (--mode train). It will save the adjusted clustering model to a file, which can then be used for validation and testing.

I will update the README later this week, I believe by Friday. Both for clustering models and Fuzzy.

But, if you have any questions or suggestions, just get in touch.

Sincerely, 
Iago

**Comment by hejiakia** [comment]
It works. Thank you so much. Looking forward about the new README.

Thanks and regards,
he

**Comment by hejiakia** [comment]
I think it's a great piece of work, and I'm eager for it to be updated soon

Thanks and regards,
he

**Comment by iag0g0mes** [comment]
Thank you very much! 

We are working on new updates to the approach. I hope we can release soon!

If you have any questions or suggestions, just let me know! 

Sincerely,
Iago
